# Journal Entry - 2024-02-28
#+TITLE: The Day of Failure
* Memembrances
Yeh, so I arrived at NADRA office for the interview and after standing in the line for an hour I was sent home without even getting in cause I had no ID card printed. In my defence I had my Birth certificate and Domicile that basically made clear that I was in fact an adult.
However instead of feeling defeted like I usually do I gathered myself better. I do am growing with my feeling, mabey slowly, but yeh. I was able to get home all by my self without any difficulty.
I didn't study when I arrived home cause I was still preety bummed by the event but did got to my usual job of teaching kids. The days at the academy are becoming more and more short and lazy as most of the kids are, due to approaching exams, are preffering to study all the themselves at home.
I have again started to journal after quitting for a long time, I do want to make it regular but I wrote mostely to get my feelings of the interview stright, specially cause I had to lie to my parents that I did actually take the exam and was let off after it cause of the ID. I didn't wanted to lie but I didn't wanted to disappoint them.
I will get I better job no matter what.
*With melencholy Wahab Ahmad*
